CREATE TABLE likes (
  userId  VARCHAR NOT NULL,
  postId  VARCHAR NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (postId) REFERENCES posts (id) ON DELETE CASCADE,
  PRIMARY KEY (userId, postId)
);
